# Tutorial 1: Tensor Contractions

https://www.tensors.net/p-tutorial-1

In [1]:
import numpy as np

In [4]:
A = np.random.rand(2,3,4)
print(A)
A.shape

[[[0.56524091 0.36378759 0.34728924 0.48109942]
  [0.73455749 0.1060462  0.15226556 0.83786516]
  [0.8989578  0.06842396 0.89238937 0.36513573]]

 [[0.32025434 0.3938792  0.37527267 0.23493556]
  [0.05806773 0.71752876 0.24456973 0.64424533]
  [0.34156465 0.83426744 0.31025337 0.65500527]]]


(2, 3, 4)

In [5]:
B = np.eye(5, 5)
print(B)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [7]:
C = np.ones((2,4,2,4))
print(C)

[[[[1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]]]


 [[[1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]]]]


In [8]:
D = np.zeros((3,5))
print(D)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [9]:
E = np.random.rand(2,3,4) + 1j * np.random.rand(2,3,4)
print(E)

[[[0.19585719+0.24023896j 0.22643355+0.5431376j  0.34192141+0.08452627j
   0.96001871+0.05007639j]
  [0.65485473+0.94621591j 0.69471566+0.56532463j 0.06570175+0.17802202j
   0.01508134+0.86279372j]
  [0.00758487+0.87326213j 0.79284359+0.8891844j  0.83632375+0.17454873j
   0.43189404+0.60043246j]]

 [[0.26898465+0.32952095j 0.25969452+0.03090918j 0.36064109+0.70713714j
   0.93663895+0.53834962j]
  [0.61431716+0.01721595j 0.07329668+0.30183814j 0.95146531+0.13221802j
   0.12970884+0.62413524j]
  [0.14373564+0.672234j   0.86828942+0.63680249j 0.90993703+0.51566541j
   0.37057538+0.53815521j]]]


## Permute

In [ ]:
P = np.arange(24).reshape(2,3,4)
print(P)

In [ ]:
P_T = P.transpose(2, 0, 1) # 4, 2, 3
print(P_T)

[[[ 0  4  8]
  [12 16 20]]

 [[ 1  5  9]
  [13 17 21]]

 [[ 2  6 10]
  [14 18 22]]

 [[ 3  7 11]
  [15 19 23]]]


In [ ]:
P_T = P.transpose(1, 2, 0) # 3, 4, 2
print(P_T)

[[[ 0 12]
  [ 1 13]
  [ 2 14]
  [ 3 15]]

 [[ 4 16]
  [ 5 17]
  [ 6 18]
  [ 7 19]]

 [[ 8 20]
  [ 9 21]
  [10 22]
  [11 23]]]


## Understanding `transpose` / permute — worked example

**The whole rule:** `b = a.transpose(perm)` means **axis `k` of `b` is axis `perm[k]` of `a`.** Everything else follows from this one sentence.

Using `P = np.arange(24).reshape(2,3,4)` (axes `a0` size 2, `a1` size 3, `a2` size 4) and `P_T = P.transpose(2,0,1)`, so `perm = (2,0,1)`.

### Step 1 — apply the rule to get the shape

Walk through `perm` left to right — each entry names which *old* axis fills that *new* slot:

| `k` (new axis) | `perm[k]` (which old axis) | size taken from `a` |
|---|---|---|
| 0 | 2 | `a.shape[2] = 4` |
| 1 | 0 | `a.shape[0] = 2` |
| 2 | 1 | `a.shape[1] = 3` |

So `b.shape = (4, 2, 3)` — matches the printed output above.

### Step 2 — apply the rule to trace one actual number

Pick an element of the output, `b[3,1,2]` (i.e. $j_0=3, j_1=1, j_2=2$). The indexing half of the rule says $i_{perm[k]} = j_k$. Plug in `perm=(2,0,1)`:

- `k=0`: `perm[0]=2` → $i_2 = j_0 = 3$
- `k=1`: `perm[1]=0` → $i_0 = j_1 = 1$
- `k=2`: `perm[2]=1` → $i_1 = j_2 = 2$

So $(i_0,i_1,i_2) = (1,2,3)$, meaning **`b[3,1,2]` must equal `a[1,2,3]`.**

Check against the printed arrays above: `P[1,2,3]` → block `1`, row `2`, entry `3` → `[20 21 22 23]`'s last entry → **23**. `P_T[3,1,2]` → block `3` is `[[3,7,11],[15,19,23]]`, row `1` is `[15,19,23]`, entry `2` → **23**. Same number — confirms the rule.

### Anchor case

Ordinary matrix transpose is just `perm=(1,0)`: axis 0 of `b` is axis 1 of `a`, axis 1 of `b` is axis 0 of `a` — rows and columns swap, the transpose already known from linear algebra. Everything above is that same idea generalized past 2 axes.

**To sanity-check on any other index:** pick any `(j0,j1,j2)` in `P_T`, solve $i_{perm[k]}=j_k$ by hand, and check it against `P`.

## Reshape

In [14]:
R = np.arange(8).reshape(2,2,2)
print(R)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
R_r = R.reshape(4,2) # multiply 2 dims to be combined into 1 dim
print(R_r)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


## Understanding `reshape` — worked example

**Definition:** reshape moves no data and computes nothing. It takes the same flat sequence of numbers underneath (stored in "C order" — the *last* axis varies fastest) and redraws the axis boundaries: merging adjacent axes together and/or splitting one axis apart, as long as the total element count stays the same before and after.

Using `R = np.arange(8).reshape(2,2,2)` (axes `a0,a1,a2` all size 2) and `R_r = R.reshape(4,2)` — this merges the first two axes `(a0,a1)` into one axis of size `2×2=4`, and leaves the last axis `a2` alone.

### Step 1 — apply the rule to get the shape

Merging adjacent axes multiplies their sizes together; an axis left out of the merge passes through unchanged:

| new axis | made from | size |
|---|---|---|
| 0 | `a0` merged with `a1` | `2×2 = 4` |
| 1 | `a2` (untouched) | `2` |

So `R_r.shape = (4, 2)` — matches the printed output above.

### Step 2 — apply the rule to trace one actual number

Pick `i0=0, i1=1, i2=1` in `R`. Because C order fills the *last-listed* axis of a merged group fastest, inside the merged pair `(i0,i1)`, `i1` is the "units" and `i0` is scaled by `a1`'s size (`n1=2`):
```
j0 = i0*n1 + i1 = 0*2 + 1 = 1
j1 = i2 = 1                      (unmerged axis passes straight through)
```
So the claim is `R[0,1,1]` must equal `R_r[1,1]`. Check against the printed arrays above: `R[0,1,1]` → `R[0]` is `[[0,1],[2,3]]`, row `1` is `[2,3]`, entry `1` → **3**. `R_r[1,1]` → row `1` is `[2,3]`, entry `1` → **3**. Same number — confirms the rule.

### Permute vs. reshape vs. contraction

| | Permute | Reshape |
|---|---|---|
| Number of legs | stays the same | can change (merge → fewer, split → more) |
| Leg sizes | stay the same, just reordered | can combine (multiply) or split (factor) |
| What happens to a number's "identity" | keeps its own old index, just under a new coordinate order | can get *merged* — one new index now encodes a whole old index-combination |
| Data movement | typically a view, often free | walks/re-cuts the flat buffer, sometimes needs a copy |
| Reversible? | always, via the inverse permutation | only if you reshape back to the original shape |

**The bigger picture:** permute and reshape are pure bookkeeping — no arithmetic ever happens, no number is computed, they only change how the *same* numbers are addressed. **Contraction** (next topic) is the one operation that's real computation: multiply-and-sum over a shared leg between tensors, producing brand-new numbers — the generalization of matrix multiplication. The usual recipe is permute → reshape → matrix-multiply → reshape back, so permute/reshape are prep work sandwiching the one step where actual math happens.

## Binary Contraction

In [ ]:
d=10
A = np.random.rand(d,d,d,d) # legs 0, 1, 2, 3 where 1 and 3 need to contract with B
B = np.random.rand(d,d,d,d) # legs 0, 1, 2, 3 where 0 and 3 need to contract with A

A_p = A.transpose(0,2,1,3) # rmbr permute has no order but we need to use one index only once so we need to permute the legs to make it easier to contract with B
B_p = B.transpose(0, 3, 1, 2)

A_s = A_p.reshape(d**2, d**2) # make it matrix s t first 2 are free riding legs
B_s = B_p.reshape(d**2, d**2) # make it matrix s t last 2 are free riding legs

C_s = A_s @ B_s # matrix multiplication

C = C_s.reshape(d,d,d,d)

print(C.shape)

(10, 10, 10, 10)
